server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://47.101.49.5:3306/eports_progress?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Kmdlmm1218.
mybatis:
  type-aliases-package: com.eports.serviceitem
  mapper-locations: classpath*:mapper/*.xml
  check-config-location: true
